---
version: '2.2'
services:
  zoo:
    image: zookeeper
  base_app:
    build: .
    environment:
      ZK_HOSTS: zoo
  app1:
    ports:
      - 5001:5000
    extends: base_app
    depends_on:
      - zoo
  app2:
    ports:
      - 5002:5000
    extends: base_app
    depends_on:
      - zoo
  app3:
    ports:
      - 5003:5000
    extends: base_app
    depends_on:
      - zoo
